---
version: "2.1"
services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DRIVE}/ombi:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.ombi.rule=Host(`need.${DOMAIN}`)
      - traefik.http.routers.ombi.middlewares=authelia@docker
    networks:
      - media-network

networks:
  media-network:
    name: media
    external: true
