version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - ${DRIVE}/qbit:/config
      - ${DRIVE}/sonarr/downloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbit.rule=Host(`qb.${DOMAIN}`)
      - traefik.http.services.qbit.loadbalancer.server.port=${WEBUI_PORT}
      - traefik.http.routers.qbit.middlewares=authelia@docker
    networks:
      - media-network

networks:
  media-network:
    name: media
    external: true
