---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091
log:
  level: debug
theme: dark
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: ${AUTHELIA_JWT_SECRET_FILE}
default_redirection_url: https://auth.${DOMAIN}
totp:
  issuer: authelia.com

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64
      
access_control:
  default_policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: ${AUTHELIA_SESSION_SECRET_FILE}
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: ${DOMAIN}  # Should match whatever your root protected domain is

  # redis:
  #   host: redis
  #   port: 6379
  #   # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
  #   # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: sheesh123 # Now required
  local:
    path: /config/db.sqlite3

notifier:
  # smtp:
  #   username: example@gmail.com
  #   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   password: example123
  #   host: smtp.gmail.com
  #   port: 587
  #   sender: example@gmail.com
  filesystem: # For sending password reset URLs to HDD incase you don't want to use SMTP
    filename: /config/notification.txt
...